import { Comic } from './comic';
export var COMICS: Comic[] = [
    {"id": 1, "name": "Marvels", "description": "Watchmen is an American comic-book limited series published by DC Comics in 1986 and 1987, and collected in 1987. The series was created by a British collaboration consisting of writer Alan Moore, artist Dave Gibbons, and colorist John Higgins. Watchmen originated from a story proposal Moore submitted to DC featuring superhero characters that the company had acquired from Charlton Comics. As Moore's proposed story would have left many of the characters unusable for future stories, managing editor Dick Giordano convinced Moore to create original characters instead."},
    {"id": 2, "name": "Avengers", "description": "Watchmen is an American comic-book limited series published by DC Comics in 1986 and 1987, and collected in 1987. The series was created by a British collaboration consisting of writer Alan Moore, artist Dave Gibbons, and colorist John Higgins. Watchmen originated from a story proposal Moore submitted to DC featuring superhero characters that the company had acquired from Charlton Comics. As Moore's proposed story would have left many of the characters unusable for future stories, managing editor Dick Giordano convinced Moore to create original characters instead."},
    {"id": 3, "name": "Superman", "description": "Watchmen is an American comic-book limited series published by DC Comics in 1986 and 1987, and collected in 1987. The series was created by a British collaboration consisting of writer Alan Moore, artist Dave Gibbons, and colorist John Higgins. Watchmen originated from a story proposal Moore submitted to DC featuring superhero characters that the company had acquired from Charlton Comics. As Moore's proposed story would have left many of the characters unusable for future stories, managing editor Dick Giordano convinced Moore to create original characters instead."},
    {"id": 4, "name": "Batman", "description": "Watchmen is an American comic-book limited series published by DC Comics in 1986 and 1987, and collected in 1987. The series was created by a British collaboration consisting of writer Alan Moore, artist Dave Gibbons, and colorist John Higgins. Watchmen originated from a story proposal Moore submitted to DC featuring superhero characters that the company had acquired from Charlton Comics. As Moore's proposed story would have left many of the characters unusable for future stories, managing editor Dick Giordano convinced Moore to create original characters instead."},
    {"id": 5, "name": "Spiderman", "description": "Watchmen is an American comic-book limited series published by DC Comics in 1986 and 1987, and collected in 1987. The series was created by a British collaboration consisting of writer Alan Moore, artist Dave Gibbons, and colorist John Higgins. Watchmen originated from a story proposal Moore submitted to DC featuring superhero characters that the company had acquired from Charlton Comics. As Moore's proposed story would have left many of the characters unusable for future stories, managing editor Dick Giordano convinced Moore to create original characters instead."},
    {"id": 6, "name": "RubberMan", "description": "Watchmen is an American comic-book limited series published by DC Comics in 1986 and 1987, and collected in 1987. The series was created by a British collaboration consisting of writer Alan Moore, artist Dave Gibbons, and colorist John Higgins. Watchmen originated from a story proposal Moore submitted to DC featuring superhero characters that the company had acquired from Charlton Comics. As Moore's proposed story would have left many of the characters unusable for future stories, managing editor Dick Giordano convinced Moore to create original characters instead."},
    {"id": 7, "name": "Flash", "description": "Watchmen is an American comic-book limited series published by DC Comics in 1986 and 1987, and collected in 1987. The series was created by a British collaboration consisting of writer Alan Moore, artist Dave Gibbons, and colorist John Higgins. Watchmen originated from a story proposal Moore submitted to DC featuring superhero characters that the company had acquired from Charlton Comics. As Moore's proposed story would have left many of the characters unusable for future stories, managing editor Dick Giordano convinced Moore to create original characters instead."},
    {"id": 8, "name": "Wathmen", "description": "Watchmen is an American comic-book limited series published by DC Comics in 1986 and 1987, and collected in 1987. The series was created by a British collaboration consisting of writer Alan Moore, artist Dave Gibbons, and colorist John Higgins. Watchmen originated from a story proposal Moore submitted to DC featuring superhero characters that the company had acquired from Charlton Comics. As Moore's proposed story would have left many of the characters unusable for future stories, managing editor Dick Giordano convinced Moore to create original characters instead."},
    {"id": 9, "name": "Hulk", "description": "Watchmen is an American comic-book limited series published by DC Comics in 1986 and 1987, and collected in 1987. The series was created by a British collaboration consisting of writer Alan Moore, artist Dave Gibbons, and colorist John Higgins. Watchmen originated from a story proposal Moore submitted to DC featuring superhero characters that the company had acquired from Charlton Comics. As Moore's proposed story would have left many of the characters unusable for future stories, managing editor Dick Giordano convinced Moore to create original characters instead."},
    {"id": 0, "name": "AntMan", "description": "Watchmen is an American comic-book limited series published by DC Comics in 1986 and 1987, and collected in 1987. The series was created by a British collaboration consisting of writer Alan Moore, artist Dave Gibbons, and colorist John Higgins. Watchmen originated from a story proposal Moore submitted to DC featuring superhero characters that the company had acquired from Charlton Comics. As Moore's proposed story would have left many of the characters unusable for future stories, managing editor Dick Giordano convinced Moore to create original characters instead."}
];
